<Workspace Version="0.8.1.1942" X="-15.8139940607316" Y="355.926304069914" zoom="0.632260924431932" Name="Home" RunType="Manual" RunPeriod="100" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="c3ddeb4a-062c-4fb9-8b04-19c6d271866c" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="904.017178511012" y="230.352490360394" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import Structure

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[0])
typelist = list()
mm = list()
for item in items:
	try: 
		typelist.append(doc.GetElement(item.Id))
		
		startPoint = (doc.GetElement(item.Id)).GetCurve().ToProtoType()
		

		mm.append(startPoint)
	except:
		#typelist.append(list())
		t="no"
		
OUT = mm</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="cafb0ca3-f2d0-4cd2-88b8-26f3b76ce292" type="Dynamo.Nodes.DSFunction" nickname="Frame.FromLine" x="1570.10406443623" y="324.051041508037" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\..\..\..\..\AppData\Roaming\Dynamo\0.8\packages\DynamoSAP\bin\DynamoSAP.dll" function="DynamoSAP.Structure.Frame.FromLine@Autodesk.DesignScript.Geometry.Line,DynamoSAP.Definitions.SectionProp,string,double">
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction guid="5353e72e-0c1b-4ead-b11f-188e2fc5e9a9" type="Dynamo.Nodes.DSFunction" nickname="SectionProp.Define" x="916.21531814687" y="481.684877082684" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\..\..\..\..\AppData\Roaming\Dynamo\0.8\packages\DynamoSAP\bin\DynamoSAP.dll" function="DynamoSAP.Definitions.SectionProp.Define@string,string,string">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction guid="46eb90d9-abba-4cb2-8953-789881311af4" type="Dynamo.Nodes.DSFunction" nickname="StructuralModel.Collector" x="1856.28701220423" y="322.988959187007" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\..\..\..\..\AppData\Roaming\Dynamo\0.8\packages\DynamoSAP\bin\DynamoSAP.dll" function="DynamoSAP.Assembly.StructuralModel.Collector@DynamoSAP.Structure.Element[]" />
    <Dynamo.Nodes.DSFunction guid="1a1082a9-e573-4ba9-a28f-b80aef031a42" type="Dynamo.Nodes.DSFunction" nickname="Bake.ToSAP" x="2293.53485375338" y="326.91896789698" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\..\..\..\..\AppData\Roaming\Dynamo\0.8\packages\DynamoSAP\bin\DynamoSAP.dll" function="DynamoSAP.Assembly.Bake.ToSAP@DynamoSAP.Assembly.StructuralModel,bool,string,bool">
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Nodes.DSFunction>
    <DSCoreNodesUI.BoolSelector guid="d76dc87b-a247-4178-ba31-fdb7896a487c" type="DSCoreNodesUI.BoolSelector" nickname="Boolean" x="2012.91306755078" y="416.858114115574" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Boolean>True</System.Boolean>
    </DSCoreNodesUI.BoolSelector>
    <DynamoSAP_UI.SectionCatalogs guid="c363d646-a62c-4f31-8e38-e03d81de14e2" type="DynamoSAP_UI.SectionCatalogs" nickname="SectionCatalogs" x="214.826389725571" y="568.408979428329" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="4:AISC14" />
    <Dynamo.Nodes.DSFunction guid="c7d07170-9523-4482-9636-341b42d62af3" type="Dynamo.Nodes.DSFunction" nickname="Family.Name" x="529.215604987903" y="467.375555251784" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.Family.Name" />
    <DSIronPythonNode.PythonNode guid="4a82ea0c-d9e1-47f6-a012-4458a508ce34" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="715.372711488026" y="467.718547907345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import Structure

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[0])
typelist = list()
mm = list()
for item in items:
	if (item != ""):
		mm.append(item)
		
OUT = mm</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="06482030-8ab6-42d0-9946-14543ac10958" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="214.439394331438" y="242.941829090207" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-00073783" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-00073784" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-0007378d" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-0007378e" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-00073796" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-00073797" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-0007379f" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737a0" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737c1" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737c2" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737d1" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737d2" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737e2" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737e3" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737f3" />
      <instance id="a82bb7de-ae86-44ce-aebe-5ebd888dd22d-000737f4" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.DSFunction guid="bea543d1-cc09-48a9-8a81-1af3bd58b44e" type="Dynamo.Nodes.DSFunction" nickname="SectionProp.Sections" x="496.343876207359" y="648.734865853734" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\..\..\..\..\AppData\Roaming\Dynamo\0.8\packages\DynamoSAP\bin\DynamoSAP.dll" function="DynamoSAP.Definitions.SectionProp.Sections@string" />
    <Dynamo.Nodes.DSFunction guid="302eeb0c-5289-4afa-bb53-eca17abd901e" type="Dynamo.Nodes.DSFunction" nickname="Element.GetParameterValueByName" x="597.421125430922" y="-134.118355535357" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="82158e6e-50c4-4303-b079-c9dfca565714" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="232.181201494228" y="-101.956455452912" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="&quot;Cross-Section Rotation&quot;;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="240464ac-e001-4016-99ec-3ebf3aa14d66" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="936.072098655972" y="-113.382781176964" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="4">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import Structure

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[0])
angles = IN[1]
elements = UnwrapElement(IN[2])
cat = UnwrapElement(IN[3])
rotationList = list()
booleanList = list()

for i in range(0,len(items)):
	if (items[i] == ""):
		rotationList.append(angles[i])
	else:
		if elements[i].Category.Id==cat.Id:
			booleanList.append(True)
		else:
			booleanList.append(False)
		
OUT = (rotationList,booleanList)
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="ff944dfc-827d-444d-bbfb-6d684b7dd9e5" type="Dynamo.Nodes.DSFunction" nickname="Frame.RevitToSAPRotationMapper" x="1319.50669801596" y="-86.2427311366943" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\..\..\..\..\AppData\Roaming\Dynamo\0.8\packages\DynamoSAP\bin\DynamoSAP.dll" function="DynamoSAP.Structure.Frame.RevitToSAPRotationMapper@double,bool" />
    <DSRevitNodesUI.Categories guid="5971debe-4f90-4433-ab2f-9bcbb2f6a99f" type="DSRevitNodesUI.Categories" nickname="Categories" x="628.157810623784" y="-2.6957335878547" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="830:StructuralColumns" />
    <Dynamo.Nodes.DSFunction guid="3534e2a7-813a-40cb-a590-09a64b667028" type="Dynamo.Nodes.DSFunction" nickname="RotationAngles" x="1136.35241311196" y="-117.318764152807" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="169be186-82b8-40ea-8626-1c00c5e62e27" type="Dynamo.Nodes.DSFunction" nickname="isColumn" x="1136.3750272478" y="-21.088131786216" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="DSCoreNodes.dll" function="DSCore.List.LastItem@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="c3ddeb4a-062c-4fb9-8b04-19c6d271866c" start_index="0" end="cafb0ca3-f2d0-4cd2-88b8-26f3b76ce292" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="cafb0ca3-f2d0-4cd2-88b8-26f3b76ce292" start_index="0" end="46eb90d9-abba-4cb2-8953-789881311af4" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5353e72e-0c1b-4ead-b11f-188e2fc5e9a9" start_index="0" end="cafb0ca3-f2d0-4cd2-88b8-26f3b76ce292" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="46eb90d9-abba-4cb2-8953-789881311af4" start_index="0" end="1a1082a9-e573-4ba9-a28f-b80aef031a42" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d76dc87b-a247-4178-ba31-fdb7896a487c" start_index="0" end="1a1082a9-e573-4ba9-a28f-b80aef031a42" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="c363d646-a62c-4f31-8e38-e03d81de14e2" start_index="0" end="bea543d1-cc09-48a9-8a81-1af3bd58b44e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c363d646-a62c-4f31-8e38-e03d81de14e2" start_index="0" end="5353e72e-0c1b-4ead-b11f-188e2fc5e9a9" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="c7d07170-9523-4482-9636-341b42d62af3" start_index="0" end="4a82ea0c-d9e1-47f6-a012-4458a508ce34" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c7d07170-9523-4482-9636-341b42d62af3" start_index="0" end="240464ac-e001-4016-99ec-3ebf3aa14d66" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4a82ea0c-d9e1-47f6-a012-4458a508ce34" start_index="0" end="5353e72e-0c1b-4ead-b11f-188e2fc5e9a9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="06482030-8ab6-42d0-9946-14543ac10958" start_index="0" end="c3ddeb4a-062c-4fb9-8b04-19c6d271866c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="06482030-8ab6-42d0-9946-14543ac10958" start_index="0" end="c7d07170-9523-4482-9636-341b42d62af3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="06482030-8ab6-42d0-9946-14543ac10958" start_index="0" end="302eeb0c-5289-4afa-bb53-eca17abd901e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="06482030-8ab6-42d0-9946-14543ac10958" start_index="0" end="240464ac-e001-4016-99ec-3ebf3aa14d66" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="302eeb0c-5289-4afa-bb53-eca17abd901e" start_index="0" end="240464ac-e001-4016-99ec-3ebf3aa14d66" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="82158e6e-50c4-4303-b079-c9dfca565714" start_index="0" end="302eeb0c-5289-4afa-bb53-eca17abd901e" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="240464ac-e001-4016-99ec-3ebf3aa14d66" start_index="0" end="3534e2a7-813a-40cb-a590-09a64b667028" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="240464ac-e001-4016-99ec-3ebf3aa14d66" start_index="0" end="169be186-82b8-40ea-8626-1c00c5e62e27" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ff944dfc-827d-444d-bbfb-6d684b7dd9e5" start_index="0" end="cafb0ca3-f2d0-4cd2-88b8-26f3b76ce292" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="5971debe-4f90-4433-ab2f-9bcbb2f6a99f" start_index="0" end="240464ac-e001-4016-99ec-3ebf3aa14d66" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="3534e2a7-813a-40cb-a590-09a64b667028" start_index="0" end="ff944dfc-827d-444d-bbfb-6d684b7dd9e5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="169be186-82b8-40ea-8626-1c00c5e62e27" start_index="0" end="ff944dfc-827d-444d-bbfb-6d684b7dd9e5" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel guid="c67d3050-2424-42f2-9036-651872627502" text="Select elements and their analytical model" x="215.443971361261" y="179.408141899093" />
    <Dynamo.Models.NoteModel guid="b4bb22cb-6504-4fe5-ab33-7fd5e491347b" text="This will read the analytical model elements" x="881.375292461875" y="182.776634557523" />
    <Dynamo.Models.NoteModel guid="f7a7dd31-e166-44f9-8c66-57f8a91065c5" text="Get the section names" x="527.844587136556" y="425.207992538715" />
    <Dynamo.Models.NoteModel guid="47f3a59e-7a69-4146-a9c5-3d517ef7bbb0" text="Remove empty elements" x="712.546383049895" y="423.271844991841" />
    <Dynamo.Models.NoteModel guid="393c5c60-feee-4d06-9d6b-663ae4ad8805" text="Select the catalog to get the sections from" x="213.632455824082" y="525.505712399505" />
    <Dynamo.Models.NoteModel guid="25a8363c-406c-48fa-8d45-de7c4beee92f" text="Define the sections" x="921.354535154994" y="421.569758542979" />
    <Dynamo.Models.NoteModel guid="691b5286-0925-4212-ab23-d0d7d41a78bf" text="Create frame from lines" x="1573.10271296319" y="168.680894083752" />
    <Dynamo.Models.NoteModel guid="a44e3366-0af0-426a-be86-a55338843d72" text="Create a DYNAMOSAP structural model" x="1867.44304317219" y="167.817085625593" />
    <Dynamo.Models.NoteModel guid="b303e72e-617e-4d42-bcdc-80fba60abe34" text="Bake to SAP" x="2305.0001553792" y="167.866129935327" />
    <Dynamo.Models.NoteModel guid="7216f690-8dc4-4e0a-8c6d-5c2dfa9abb2a" text="Get angles and if the elements are columns" x="912.772080638696" y="-183.368519790151" />
  </Notes>
  <Annotations />
</Workspace>